### PR TITLE
Feature/yvCurve-MIM vault

### PR DESCRIPTION
**Pull request by TBouder**
## What it does ✨
Add the yvCurve MIM vault to the USD metapool

## How to test ✅
You should be able to get tokens from Panda's script and then try to swap in one way and the other.

### CODE REVIEW

**Comment by fameal** [comment]
USDP --> MIM: OK
MIM --> USDP: NOOK. Internal JSON-RPC error. I reloaded and retried multiple times.

Screenshot 2021-09-13 at 11 14 36

**Comment by pandadefi** [comment]
Can we merge this?

**Comment by pandadefi** [comment]
I am not able to swap from 3pool to MIM since MIM uses 3Pool that should be possible right?

**Review by saltyfacu — APPROVED** [review]
lgtm

**Pull request merged**
